project:
  type: website
  output-dir: .

website:
  title: "Felina Leng"
  navbar:
    background: primary
    search: true
    pinned: true
    left:
      - text: "My Vision"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - projects.qmd
      - publications.qmd
    right: 
      - contact.qmd
    tools:
      - icon: linkedin
        href: www.linkedin.com/in/felina-leng-02a292232
  page-footer: 
    center: "Copyright 2025, Felina Leng"
    background: light
    foreground: primary
  announcement: 
    icon: info-circle
    dismissable: true
    content: "This website is new and still under construction."
    background: warning
    position: below-navbar

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual


